### ISSUE TITLE
ALTA EJERCICIO GASTOS Y FACTURAS

### ISSUE THREAD

**Issue by anacid** [gregorioruiz/Arasti#14]
Cuando el ejercicio está ya dado de alta, en GASTOS tenemos que definir los porcentajes y las cuentas de IVA, estos datos se pueden pasar del ejercicio anterior, o puede dar algún error?
![ScreenClip.png](https://zube.io/files/gregorioruiz/2e0478e943b7f21006378014f538dcb5.png)

**Comment by anacid** [comment]
Cuando el ejercicio ya esta dado de alta, en FACTURAS, se pueden pasar los datos de impuestos y series del ejercicio anterior.
![ScreenClip.png](https://zube.io/files/gregorioruiz/04c361f441ee9e4c0a86ac9c4550ad18.png)

**Comment by gregorioruiz** [comment]
​Las cuentas de iva y los porcentajes los tienen que meter a mano este año,
porque les vamos a cambiar el programa para que funcione como en las
facturas​.
En cuanto a las otras pestañas, las retenciones también las definiremos
como el iva, así que no hace falta que pasen

Las de CEE creo que mejor las conservamos y las de cuentas, sí que deberían
pasar.




Enviado con MailTrack
<https://mailtrack.io/install?source=signature&lang=es&referral=gregorio@cidmultimedia.es&idSignature=23>

El 15 de diciembre de 2015, 11:12, anacid <notifications@github.com>
escribió:

> Cuando el ejercicio está ya dado de alta, en GASTOS tenemos que definir
> los porcentajes y las cuentas de IVA, estos datos se pueden pasar del
> ejercicio anterior, o puede dar algún error?
> [image: ScreenClip.png]
> <https://camo.githubusercontent.com/60ab9c45f12adcea278605af9f392c90aee55d8c/68747470733a2f2f7a7562652e696f2f66696c65732f677265676f72696f7275697a2f32653034373865393433623766323130303633373830313466353338646362352e706e67>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gregorioruiz/Arasti/issues/14>.
>



-- 
Un saludo,

Gregorio Ruiz Vecino
Cid Multimedia S.L.

**Comment by gregorioruiz** [comment]
GASTOS
Hacer el alta de los impuestos y las series. Al menos una serie.
Hacer también retenciones igual que impuestos, variable.
