### ISSUE TITLE
2.- Menú de Gastos.-Cuando damos de alta un proveedor, en la pantalla donde metemos los datos, en el apartado correspondiente a CIF, no aparece dicho epígrafe. Sería necesario.También que al dar intro saltara al siguiente campo sin tener que ir con el ratón.

### ISSUE THREAD

**Issue by gregorioruiz** [gregorioruiz/Arasti#2]

**Comment by gregorioruiz** [comment]
![ScreenClip.png](https://zube.io/files/gregorioruiz/fda42ba142ad2890a8b867dbd7c8c75a.png)

![ScreenClip.png](https://zube.io/files/gregorioruiz/587e0e24bc3668a9b6e86f17b747a5f1.png)

**Comment by anacid** [comment]
He probado a dar de alta un proveedor, y puedo perfectamente, y si esta el CIF.
Dime si lo he entendido bien.
