### ISSUE TITLE
4.- No está diseñado el modelo de factura electrónica. Ahora mismo si se imprime no sale bien.

### ISSUE THREAD

**Issue by gregorioruiz** [gregorioruiz/Arasti#3]

**Comment by gregorioruiz** [comment]
Modelo de factura remitido por Diana

![ScreenClip.png](https://zube.io/files/gregorioruiz/69a11751cb5e8f858906b30850d1e699.png)

**Comment by anacid** [comment]
Ya lo tienes preparado en el programa para probar?

**Comment by gregorioruiz** [comment]
No, pero ya que preguntas, tengo una duda: de dónde sale ese concepto que ponen entre el cliente y las líneas?

**Comment by anacid** [comment]
Pues no se, porque cuando yo les hice las facturas para enviar a facturaE lo poniamos todo en concepto, quizás lo consideren como el título del contrato.

**Comment by gregorioruiz** [comment]
Hecho. Prueba por si se me ha pasado algún detalle y se lo actualizamos. Gracias.

**Comment by anacid** [comment]
Probado a imprimir una factura, el modelo es distinto a lo que ellos nos han pasado. Y desde "imprimir" directamente imprime la factura, debemos de poner también para que simplemente la puedan ver por pantalla, tal como nos han pedido.
