### ISSUE TITLE
7.- En el programa de nóminas, en menú centros, al dar de alta un nuevo centro, la cuenta de contabilidad donde debería de ir al hacer el traspaso no aparece.

### ISSUE THREAD

**Issue by gregorioruiz** [gregorioruiz/Arasti#5]

**Comment by gregorioruiz** [comment]
![ScreenClip.png](https://zube.io/files/gregorioruiz/cc84b94bead3670e943c456587fa8a85.png)

**Comment by anacid** [comment]
He estado comprobando este punto, y creo que lo tienen explicado el funcionamiento en el manual que les pase, adjunto el detalle. Ya me dices.

![ScreenClip.png](https://zube.io/files/gregorioruiz/558c8355b8ba55b990c9ebac1011b034.png)

![ScreenClip.png](https://zube.io/files/gregorioruiz/194bdf03650e9cd46a00db32e01e2e12.png)
![ScreenClip.png](https://zube.io/files/gregorioruiz/bc12229afdf2e7aa0a5ac71b5a41727c.png)
